# Generated by Django 4.2.11 on 2024-07-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='123@gmail.com', max_length=254),
        ),
    ]
