# Generated by Django 4.2.11 on 2024-07-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_address_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='harshit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('study', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
