# Generated by Django 4.2.11 on 2024-07-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_harshit'),
    ]

    operations = [
        migrations.AddField(
            model_name='harshit',
            name='age',
            field=models.IntegerField(default=21),
        ),
    ]
