# Generated by Django 4.2.11 on 2024-07-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcp_name', models.CharField(max_length=100)),
                ('rcp_description', models.TextField()),
                ('image', models.ImageField(upload_to='rcp')),
            ],
        ),
    ]
