# Generated by Django 4.2.11 on 2024-07-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rcp',
            old_name='image',
            new_name='rcp_image',
        ),
    ]
