# Generated by Django 4.2.11 on 2024-07-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_rename_image_rcp_rcp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcp',
            name='rcp_image',
            field=models.ImageField(upload_to='receiptes'),
        ),
    ]
