# Generated by Django 4.2.11 on 2024-07-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_alter_rcp_rcp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcp',
            name='rcp_description',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='rcp',
            name='rcp_image',
            field=models.ImageField(editable=False, upload_to='receiptes'),
        ),
        migrations.AlterField(
            model_name='rcp',
            name='rcp_name',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
