# Generated by Django 4.2.11 on 2024-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_alter_rcp_rcp_description_alter_rcp_rcp_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcp',
            name='rcp_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rcp',
            name='rcp_image',
            field=models.ImageField(upload_to='receiptes'),
        ),
        migrations.AlterField(
            model_name='rcp',
            name='rcp_name',
            field=models.CharField(max_length=100),
        ),
    ]
