# Generated by Django 4.2.11 on 2024-08-08 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vege', '0005_alter_rcp_rcp_description_alter_rcp_rcp_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
